name: Stock Price Prediction CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
      

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Create and activate virtual environment
      run: |
        python -m venv env
        source env/bin/activate
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install Pandas
      run: pip install pandas
    - name: Train model
      run: |
        source env/bin/activate
        python models/train.py
    - name: Test model
      run: |
        source env/bin/activate
        python models/test.py
    - name: Run unit tests
      run: |
        source env/bin/activate
        python -m unittest discover -s tests

  deploy:
    needs: train-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Create and activate virtual environment
      run: |
        python -m venv env
        source env/bin/activate
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Deploy model
      run: |
        source env/bin/activate
        python models/deploy.py

