image: python:3.8 

definitions: 
  variables: 
    NGROK_URL : 'https://5de7-2405-201-d017-b190-251a-33b6-a93a-d31c.ngrok-free.app'

pipelines: 
  branches: 
    main:
    - step: 
        name: Train and Test Model 
        script: 
          — pip install —r requirements. txt 
          — python train. py 
          - python test.py
          - python -m unittest discover -s "tests"
    — step: 
        name: Deploy Model 
        script: 
          — pip install —r requirements. txt 
          — python deploy.py & 
          — sleep 5 # Give Flask some time to start 
          - echo "The ngrok URL is $NGROK_URL" 
